listener 1883
protocol mqtt
listener 9001
protocol websockets
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true
max_connections -1
max_queued_messages 1000
allow_anonymous true
max_queued_bytes 0
message_size_limit 0
max_inflight_messages 20
max_keepalive 65535
